### ISSUE TITLE
Error when change airflow on ventilation unit

### ISSUE THREAD

**Issue by hwikene** [perara/python-systemair-savecair#4]
I get this when i change from "Low" to "High" airflow direct on the unit. 

`
2018-10-22 12:45:54 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 232, in async_update_ha_state
    state = self.state
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/climate/__init__.py", line 210, in state
    if self.is_on is False:
  File "/config/custom_components/climate/systemair_savecair.py", line 184, in is_on
    return int(self._client.data["main_airflow"]) - 1 > 0
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

**Comment by perara** [comment]
I'll take a look. Thanks!
